services:
  express_app:
    build: .
    command: pm2-runtime start app.js --name "pogakco-backend"
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      NODE_ENV: production
